version: "3.9"

services:
  web:
    build: .
    command:
      - /bin/sh
      - '-c'
      - '/usr/src/app/docker-entrypoint.sh'
    volumes:
      - .:/usr/src/app/
      - data:/usr/src/app/data/
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  data: